name: haskex-utils
version: 0.0.0.0
github: "epsilon-productions/haskex-utils"
license: MIT
author: "Epsilon Productions"
maintainer: "not@available.com"
copyright: "2020 Epsilon Productions"

extra-source-files:
  - README.md
  - CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/epsilon-productions/haskex-utils#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

# executables:
#   haskex-utils-exe:
#     main: Main.hs
#     source-dirs: app
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - haskex-utils

# tests:
#   haskex-utils-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options:
#       - -threaded
#       - -rtsopts
#       - -with-rtsopts=-N
#     dependencies:
#       - haskex-utils
